[package]
name = "triad"
version = "0.1.0"
authors = ["Thomas Roehl <Thomas.Roehl@fau.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foreach = "0.3.0"
rayon = "1.0.3"




